### ISSUE TITLE
omxplayer-sync -muv synctest.mp4 fails

### ISSUE THREAD

**Issue by ooftv** [turingmachine/omxplayer-sync#103]
I was playing around with this yesterday on raspian-lite and everything was working, but today I created a new SD card for the same pi with raspian-lite and can't get anything to play.

Using your sample file:

omxplayer-sync -muv synctest.mp4

Traceback (most recent call last):
  File "/usr/bin/omxplayer-sync", line 394, in <module>
    OMXPlayerSync().run()
  File "/usr/bin/omxplayer-sync", line 120, in __init__
    self.sock = self.init_socket()
  File "/usr/bin/omxplayer-sync", line 343, in init_socket
    sock.bind(('0.0.0.0', PORT))
OSError: [Errno 98] Address already in use

Any ideas? Not sure what I did differently this time.

**Comment by ooftv** [comment]
Turns out it was related to Python. 

ps -fA | grep python

look for the pid of the process run by omxplayer-sync
root       395     1  0 May23 ?        00:00:00 python3 /usr/bin/omxplayer-sync
for me it was 395

kill -9 395

I found this from here: https://medium.com/@sanzidkawsar/the-python-flask-problem-oserror-errno-98-address-already-in-use-flask-49daaccaef4f
