### ISSUE TITLE
launch omxplayer-sync on startup 

### ISSUE THREAD

**Issue by TheAffair** [turingmachine/omxplayer-sync#114]
Hello- I installed omxplayer-sync on B plus running Stretch.  Master works fine.  Slave returns the errors below on startup.  Can you provide a solve or point me in the right direction please?

I am launching omxplayer-sync with a bash script on start up using this script:
#!/bin/bash
echo startup.sh : Launching omxplayer-sync:
omxplayer-sync -muv hdmi /home/pi/Vides/DFS.mp4

Error:
Traceback (most recent call last)
File "/usr/bin/omxplayer-sync", line 394, in <module>
  OMXplayerSync().run()
File "/usr/bin/omxplayer-sync", line 182, in run
  self.play_file(self.playlist[self.playlist.index])
File "/usr/bin/omxplayer-sync", line 209, in play file
  preexec_fn=os.setsid, stdout=DEVNULL, stderr=DEVNULL, stdin=DEVNULL)
File "/usr/lib/python3.7/subprocess.py", line 775, in_init_
  restore_signals, start_new_session)
File "/usr/lib/python3.7/subprocess.py", line 1522, in_execute_child
  raise child_exception_type(errnonum, err_msg, err_filename)
FileNotFoundError: [Errno 2} No such file or directory: 'omxplayer': 'omxplayer'

**Comment by himijendrix24** [comment]
Wrong video file pathname?

**Comment by exidyboy** [comment]
On 14/07/2021, at 7:36 AM, TheAffair wrote:

> 
> Hello- I installed omxplayer-sync on B plus running Stretch. Master works fine. Slave returns the errors below. Can you provide a solve or point me in the right direction please?
> 
> I am launching omxplayer-sync with a bash script on start up which runs master perfectly using this script:
> #!/bin/bash
> echo startup.sh : Launching omxplayer-sync:
> omxplayer-sync -muv hdmi /home/pi/Vides/DFS.mp4

Typo is folder name "Vides"?
Are you using -luv on the slave instead of -muv?

**Comment by TheAffair** [comment]
> Wrong video file pathname?

Good catch! Thank you. But still not working.  The error return seems to reflect an issue with omxplayer-sync not existing in the /bin location.

**Comment by TheAffair** [comment]
Yes I am using -luv on slave and -muv on master.  I was able to copy the working disk image and change the slave to -luv which solved the issue. However when installing omxplayer – sync on a fresh Stretch or Jesse release I get the same error message.

**Comment by barlaensdoonn** [comment]
FYI i'd recommend removing the -v flag when launching on startup. It spits out a lot of lines that are useful when testing but aren't needed during automated runs.

**Comment by TheAffair** [comment]
> FYI i'd recommend removing the -v flag when launching on startup. It spits out a lot of lines that are useful when testing but aren't needed during automated runs.

Good call.  Thank you!

**Comment by fadetofadh** [comment]
Hi, I am new here. I got a job that require me to in touch with Raspberry Pi. I guess It's Pi4.

I wonder how to create script for autoplay like that bash you did. I only know to input line command on nano rc.local.

> Hello- I installed omxplayer-sync on B plus running Stretch. Master works fine. Slave returns the errors below on startup. Can you provide a solve or point me in the right direction please?
> 
> I am launching omxplayer-sync with a bash script on start up using this script: #!/bin/bash echo startup.sh : Launching omxplayer-sync: omxplayer-sync -muv hdmi /home/pi/Vides/DFS.mp4
> 
> Error: Traceback (most recent call last) File "/usr/bin/omxplayer-sync", line 394, in OMXplayerSync().run() File "/usr/bin/omxplayer-sync", line 182, in run self.play_file(self.playlist[self.playlist.index]) File "/usr/bin/omxplayer-sync", line 209, in play file preexec_fn=os.setsid, stdout=DEVNULL, stderr=DEVNULL, stdin=DEVNULL) File "/usr/lib/python3.7/subprocess.py", line 775, in_init_ restore_signals, start_new_session) File "/usr/lib/python3.7/subprocess.py", line 1522, in_execute_child raise child_exception_type(errnonum, err_msg, err_filename) FileNotFoundError: [Errno 2} No such file or directory: 'omxplayer': 'omxplayer'
